# hack for mingw, prefer libz.a in lib/ folder over some .dll
FIND_LIBRARY( ZLIB_LIBRARY NAMES libz.a z zlib )
FIND_LIBRARY( SDL2_LIBRARY NAMES libSDL2.a )

# get required pacakges
FIND_PACKAGE( SDL2 )
FIND_PACKAGE( EGL )
FIND_PACKAGE( OSMESA )
FIND_PACKAGE( PNG        REQUIRED )
FIND_PACKAGE( OpenGL     REQUIRED )

IF ( NOT USE_API )
  IF ( SDL2_FOUND )
  	SET ( USE_API "SDL2" )
  ELSEIF ( OSMESA_FOUND )
  	SET ( USE_API "OSMESA" )
  ELSEIF ( EGL_FOUND )
  	SET ( USE_API "EGL" )
  ELSE ()
  	MESSAGE(ERROR "Could not find SDL2, EGL or OSMesa")
  ENDIF ()
ENDIF ()

IF ( ${USE_API} STREQUAL "SDL2" )
  MESSAGE("Using SDL2...")
  SET (API_LIBRARIES ${SDL2_LIBRARY_TEMP})
  SET (API_INCLUDES ${SDL2_INCLUDE_DIR})
  ADD_DEFINITIONS(-DGLEW_STATIC)
ELSEIF(${USE_API} STREQUAL "OSMESA")
  MESSAGE("Using OSMESA...")
  SET (API_LIBRARIES ${OSMESA_LIBRARY})
  SET (API_INCLUDES ${OSMESA_INCLUDE_DIR})
  ADD_DEFINITIONS(-DGLEW_STATIC -DGLEW_OSMESA)
ELSEIF(${USE_API} STREQUAL "EGL")
  MESSAGE("Using EGL...")
  SET (API_LIBRARIES ${EGL_LIBRARIES})
  SET (API_INCLUDES ${EGL_INCLUDE_DIRS})
  ADD_DEFINITIONS(-DGLEW_STATIC -DGLEW_EGL)
ENDIF()

SET( LIBRARIES 
  ${API_LIBRARIES}
  ${OPENGL_LIBRARIES}
  ${PNG_LIBRARY}
  ${ZLIB_LIBRARY}
)

IF ( WIN32 )
  SET( LIBRARIES ${LIBRARIES} winmm imm32 version ws2_32 )
ENDIF ()
